config/routes.rb
Yatapi::Application.routes.draw do

  root to: 'home#index'
  get '/tour', to: 'tour#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @appName = 'yatapi'
  end
end

app/controllers/tour_controller.rb
class TourController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tour_helper.rb
module TourHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1>&#10003;<%= @appName %></h1>
  </div>
</div>

<hr />

<div class="row">
  <div class="large-6 columns">
    <h2>See it in action</h2>
    <p>
      Check out our interactive tour and create
      your first tasks.
    </p>
    <p>
    <a href="<%= tour_path %>" class="button">Start the interactive tour</a>
    </p>
  </div>

  <div class="large-6 columns">
    [application screenshot]
  </div>
</div>

<hr />

<div class="row">
  <div class="large-12 columns">
    Companies already using this app
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tour/index.html.erb
<h1>&#10003;yatapi</h1>

<div class="row">
  <div class="large-12 columns">

    <div class="tour yatapi-tasks">
      <div class="row">
        <div class="large-12 columns tasklist">
          <h4>Tasks to do:</h4>
        </div>
      </div>
      <input class="yatapi-addtask-input" type="text" placeholder="Add a new task" />
    </div>
    <p id="tour-guide" class="centered">
      Try to add a new task by writing something in the input box and pressing enter.
    </p>
  </div>
</div>